URL_SERVICE = "https://cnt-e96aba5f-af00-4fc4-a005-750c17db3df1.containerhub.tripleten-services.com"
DOC_PATH = "/docs/"
CREATE_USER_PATH = "/api/v1/users/"
KITS_PATH = "/api/v1/kits/"
KITS_TABLE_PATH = "/api/db/resources/kit_model.csv"
