URL_SERVICE = "https://cnt-d549bd86-43be-4dcb-8ebd-0c56d8caa305.containerhub.tripleten-services.com"
DOC_PATH = "/docs/"
CREATE_USER_PATH = "/api/v1/users/"
KITS_PATH = "/api/v1/kits/"
KITS_TABLE_PATH = "/api/db/resources/kit_model.csv"
